version: '1.0'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    ports:
      - '5433:5432'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - ./src:/server/src
